### PR TITLE
Fix downscaling mechanism by checking blank tiles

### PR DESCRIPTION
**Pull request by alfmarcua**
Downscaling issue fixed by checking blank tiles https://github.com/mapproxy/mapproxy/issues/687

### CODE REVIEW

**Comment by weskamm** [comment]
Tests seems to fail currently, please have a look. Besides i am not sure if the problem is fixed by only handling RGBA images.

**Comment by weskamm** [comment]
closing due to inactivity, feel free to reopen

**Comment by alfmarcua** [comment]
Please @weskamm reopen the pull request since the issue it is not solved on master branch.

I have fixed all the errors of the test so I think it is ready to be merged.

**Comment by weskamm** [comment]
Yeah i was waiting for an example configuration, thanks for that

**Comment by hannesaddec** [comment]
@weskamm anything else from our side to be done ? could it be merged ?

**Comment by weskamm** [comment]
I hope to find some time for a detailed review in november

**Pull request closed without merging**
