### PR TITLE
S3 Performance: s3 http get

### PR DESCRIPTION
**Pull request by bkuster**
### Background
Using `Mapproxy` on an AWS hosted EC2 to provide cached data using **S3** storage.

### Issue
When using the S3 cache, the response times can be high (~300-500ms for a _cached_ tile when requesting from localhost). One of the reasons for this is the underlying AWS API which is used to `GetObject`. Checking the debug log, a couple hundred ms are used just to assume the required AWS role.

### Proposal
By configuring the `Bucket Policy` to allow any principal from a specific VPC S3 endpoint (eg. from the VPC the EC2 is runngin in)  to `GetObject`, the bucket can be accessed over `http` instead of the AWS SDK, bypassing the need for `boto` to do its thing. This has brought down the request time on localhost to ~40ms.

### Solution
The S3 cache can now be configured with `use_http_get`. If specified, requests to `GetObject` are requested using `urllib2` instead of `boto`

### CODE REVIEW

**Comment by bkuster** [comment]
Ok, so my Python is a bit rusty. I'll update to urrlib3...

**Comment by olt** [comment]
Thanks for your contribution. I assume these delays are an AWS edge case within your setup, since no one else reported such delays.
Right now I'm -1 for this patch as it makes the code more complex (urlib2 and boto). Can you find a cleaner solution to speed this up with boto?

**Comment by bkuster** [comment]
thanks for the reply @olt.

I'm not sure to what extent this is an edge case. If you use an AWS S3 VPCE in your setup to access S3, you do not need boto to build up IAM on every `GetObject` request. Maybe there is a way to circumvent this with boto, but sofar I haven't found a solution. To my knowledge, all AWS SDKs assume instance roles when called from an EC2. 

Nonetheless, I understand your code complexity concern. Since no one else has reported such an issue, maybe there is an alternative solution?

**Comment by walkermatt** [comment]
When I originally worked on an S3 backend my main concern was the performance, I'll see about finding some time to test as we've several cases where I'd be interested in using S3 if the performance is acceptable.

**Comment by walkermatt** [comment]
I've had a chance to do some testing, the good news is using http for GET operations when using an S3 endpoint within a VPC improves performance significantly :tada:

Some results below which support this.

All requests are executed 50 times and the mean request time taken. All caches are configured to use a fully seeded file cache as their source.

The `file` cache is using a local file cache, `s3_boto` is an S3 cache with `use_http_get: false` while `s3_http` is an S3 cache with `use_http_get: true`.

### Empty cache

Cache is cleared before each request. Both `s3_boto` and `s3_http` will use Boto3 to PUT tiles.

#### Single tile

**seconds** | **cache** | **url**
-- | -- | ---
  0.165 | file | http://localhost:8080/tms/1.0.0/ospremium_file/ospremium_grid/13/5717/5742.png
  0.83 | s3_boto | http://localhost:8080/tms/1.0.0/ospremium_s3_boto/ospremium_grid/13/5717/5742.png
  0.723 | s3_http | http://localhost:8080/tms/1.0.0/ospremium_s3_http/ospremium_grid/13/5717/5742.png

#### Multi-tile WMS

**seconds** | **cache** | **url**
-- | -- | ---
  0.031 | file | http://localhost:8080/service?LAYERS=ospremium_file&FORMAT=image%2Fpng&SRS=EPSG%3A27700&EXCEPTIONS=application%2Fvnd.ogc.se_inimage&TRANSPARENT=TRUE&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&BBOX=-4352000,-3840000,4352000,3840000&WIDTH=680&HEIGHT=600
  0.756 | s3_boto | http://localhost:8080/service?LAYERS=ospremium_s3_boto&FORMAT=image%2Fpng&SRS=EPSG%3A27700&EXCEPTIONS=application%2Fvnd.ogc.se_inimage&TRANSPARENT=TRUE&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&BBOX=-4352000,-3840000,4352000,3840000&WIDTH=680&HEIGHT=600
  0.424 | s3_http | http://localhost:8080/service?LAYERS=ospremium_s3_http&FORMAT=image%2Fpng&SRS=EPSG%3A27700&EXCEPTIONS=application%2Fvnd.ogc.se_inimage&TRANSPARENT=TRUE&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&BBOX=-4352000,-3840000,4352000,3840000&WIDTH=680&HEIGHT=600

### Seeded

Cache pre-seeded, all cache requests are therefore reads. 

#### Single tile

**seconds** | **cache** | **url**
-- | -- | ---
  0.005 | file | http://localhost:8080/tms/1.0.0/ospremium_file/ospremium_grid/13/5717/5742.png
  0.089 | s3_boto | http://localhost:8080/tms/1.0.0/ospremium_s3_boto/ospremium_grid/13/5717/5742.png
  0.033 | s3_http | http://localhost:8080/tms/1.0.0/ospremium_s3_http/ospremium_grid/13/5717/5742.png

#### Multi-tile WMS

**seconds** | **cache** | **url**
-- | -- | ---
  0.014 | file | http://localhost:8080/service?LAYERS=ospremium_file&FORMAT=image%2Fpng&SRS=EPSG%3A27700&EXCEPTIONS=application%2Fvnd.ogc.se_inimage&TRANSPARENT=TRUE&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&BBOX=-4352000,-3840000,4352000,3840000&WIDTH=680&HEIGHT=600
  0.279 | s3_boto | http://localhost:8080/service?LAYERS=ospremium_s3_boto&FORMAT=image%2Fpng&SRS=EPSG%3A27700&EXCEPTIONS=application%2Fvnd.ogc.se_inimage&TRANSPARENT=TRUE&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&BBOX=-4352000,-3840000,4352000,3840000&WIDTH=680&HEIGHT=600
  0.04 | s3_http | http://localhost:8080/service?LAYERS=ospremium_s3_http&FORMAT=image%2Fpng&SRS=EPSG%3A27700&EXCEPTIONS=application%2Fvnd.ogc.se_inimage&TRANSPARENT=TRUE&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&BBOX=-4352000,-3840000,4352000,3840000&WIDTH=680&HEIGHT=600

**Comment by bkuster** [comment]
thanks for taking the time @walkermatt ! fyi we have been using this branch in production for quite some time now and have had no issues so far. any chance of reconsidering this patch @olt ?

**Comment by asafMasa** [comment]
Why wasn't this branch merged?

**Comment by syncush** [comment]
Any updates?

**Comment by weskamm** [comment]
At least the documentation for the new option is missing. So if anyone wants to contribute, feel free to do so

**Comment by weskamm** [comment]
Thanks for contribution, rebased and added documentaiton in https://github.com/mapproxy/mapproxy/pull/788

**Pull request closed without merging**
