### PR TITLE
fix for proxying feature_count param in wmts getfeatureinfo request

### PR DESCRIPTION
**Pull request by arbakker**
https://github.com/mapproxy/mapproxy/issues/405

### CODE REVIEW

**Comment by olt** [comment]
Thanks. Can you add a testcase to https://github.com/mapproxy/mapproxy/blob/master/mapproxy/test/system/test_wmts.py

**Comment by arbakker** [comment]
I added a test case for a getfeatureinfo request with feature_count parameter.

**Comment by arbakker** [comment]
The Travis build failed, but only for `Python: 2.7 USE_LATEST_PILLOW=1`. 

The following test failed:
``` 
mapproxy/test/system/test_wms.py::TestWMS100::test_get_map FAILED        [ 30%]
```
This seems unrelated to the test case I added. Any idea what is going on?

**Comment by olt** [comment]
Thanks!

**Pull request merged**
