### PR TITLE
Redis cache authentication

### PR DESCRIPTION
**Pull request by bmanojlovic**
Default settings allow use of REDIS only without authentication which in most cases is not desirable in multiuser clusters or when using any kind of "hosted" redis instances, this change adds authentication to existing codebase.

### CODE REVIEW

**Comment by shimoncohen** [comment]
Hi, this looks like it is meant to solve #353, is that correct?

**Comment by bmanojlovic** [comment]
You are correct this patch adds authentication for redis.

**Comment by shimoncohen** [comment]
What about using a `CERT` file when connecting to a `Redis` cluster? Do you think this is in the scope of this PR?
https://redis.io/docs/clients/python/
https://redis-py.readthedocs.io/en/stable/examples/ssl_connection_examples.html
https://docs.selectel.com/cloud/managed-databases/redis/connect-to-cluster/

**Comment by bmanojlovic** [comment]
at this moment answer is no,
it should be doable to add it,
 but can't promise time frame for it (lets say i have "added it to my list of TODOs" )
 answer is yes it is in scope as that is authentication but again time is limiting factor

**Comment by shimoncohen** [comment]
@weskamm Can you please review this PR? This can be really helpful :)

**Comment by weskamm** [comment]
Looks good, thanks!

**Pull request merged**
