### PR TITLE
[mapnik] python 3 compatibility

### PR DESCRIPTION
**Pull request by drnextgis**
Fixes https://github.com/mapproxy/mapproxy/issues/500

### CODE REVIEW

**Comment by ramunasd** [comment]
@drnextgis can You squash commits? It should trigger updated CI pipeline.

**Comment by drnextgis** [comment]
Squashed.

**Comment by drnextgis** [comment]
@ramunasd CI is happy now. I had to add a small change to `mapproxy/cache/tile.py` in order to overcome [this](https://github.com/mapproxy/mapproxy/runs/4595329875?check_suite_focus=true) issue.

**Comment by ramunasd** [comment]
LGTM, @weskamm can we merge this?

**Comment by weskamm** [comment]
of course feel free to do so

**Pull request merged**
