### PR TITLE
Improve riak backend

### PR DESCRIPTION
**Pull request by ramunasd**
- support for python 3.x
- upgraded dependencies
- documentation improvements
- faster object write operations
- request timeout same as for http request

### CODE REVIEW

**Comment by ramunasd** [comment]
Tests fails only in travis and only during pbc requests. I tried same riak and lib versions but can't reproduce this certain error.

**Comment by ramunasd** [comment]
Hi @olt, is there any chances to merge this before version 1.8.2 ?

**Comment by olt** [comment]
What steps need to be done to enable the Protobuf tests?

**Comment by ramunasd** [comment]
Hi @olt ,
if You want enable Protobuf tests then it needs to add additional environment variable, something like this `MAPPROXY_TEST_RIAK_PBC=pbc://localhost:8087`

**Comment by olt** [comment]
I meant the Travis tests. I don't have a working Riak setup, but it would be great to have it fully tested before the next release.

**Comment by ramunasd** [comment]
As You see, it fails, but not because of mapproxy. Something is wrong with travis setup.

**Comment by ramunasd** [comment]
It's known issue - https://github.com/basho/riak-python-client/issues/399
Next riak-python version will handle that issue.

**Pull request closed without merging**
