### PR TITLE
[WIP] Create install_mac.rst

### PR DESCRIPTION
**Pull request by PowerPan**
Installing MapProxy on Mac.

it is really easy 

brew install proj
sudo pip install MapProxy

and it runs ;)

Maybe this file nee additional changes. Feel Free to comment, I will change it

### CODE REVIEW

**Comment by olt** [comment]
Thanks a lot.

Much of this is a duplicate of the Linux installation guide and this makes it hard to maintain. 
The documentation should only mention the differences between a _normal_ installation and  installation on Mac, similar to https://mapproxy.org/docs/nightly/install_windows.html

**Comment by PowerPan** [comment]
@olt Looks better now? or?

**Comment by olt** [comment]
This is now a bit too terse. Please see https://mapproxy.org/docs/nightly/install_windows.html
It needs a few words about homebrew and links. What about virtualenv? Does pip work without sudo?
Also, there are still a few typos and it is not valid reStructuredText.

**Comment by weskamm** [comment]
Thanks for contribution, but i am going to close this due to inactivity

**Pull request closed without merging**
