### PR TITLE
Fix debian packaging

### PR DESCRIPTION
**Pull request by landryb**
Hi,

ive tried the make builddeb target on 1.7.1 tag to see it fail - so i've just updated the patches and the changelog - packages for me here.

### CODE REVIEW

**Comment by landryb** [comment]
For what it's worth, make builddeb target still fails the same on 1.8.0.

**Comment by landryb** [comment]
cherry-picking commit 968f144a40d7abf724a86a7f1eff948ad8a62ac4 in this PR on top of 1.8.0 git tag allows make builddeb to succeed.

**Comment by olt** [comment]
I've updated the font_dir patch in 1.8.x and master branch.

**Comment by landryb** [comment]
Thanks ! You could have cherrypicked my commit to keep authorship.. just sayin', not a big deal :)

**Comment by olt** [comment]
Oh, I did't used your patch. I've updates the patch while building new packages for the OSGeoLive DVD.
Patching patches is no fun :)

**Pull request closed without merging**
