### PR TITLE
Enable riak cache tests on travis-ci

### PR DESCRIPTION
**Pull request by ramunasd**
Fix for #415

### CODE REVIEW

**Comment by olt** [comment]
Thanks. Not sure why the CI runs are not showing up here, but they did run https://travis-ci.org/mapproxy/mapproxy/pull_requests and somehow fail.

(You can ignore the Python 2.7/USE_LATEST_PILLOW=1 errors).

**Comment by ramunasd** [comment]
Looks like travis-ci does not like when git push is forced and previous build is not finished.
I will trigger build later, seems everything will be ok.

**Comment by ramunasd** [comment]
Ready.
Only 2.7 with latest pillow fails.

**Comment by olt** [comment]
Thanks for the quick fix!

**Pull request merged**
