### PR TITLE
create json legend for multiple layers

### PR DESCRIPTION
**Pull request by stijn-at-work**

### CODE REVIEW

**Comment by stijn-at-work** [comment]
This is an improvement to the json legend pull request merged previously. 
The old code was only able to create a json legend for one layer. The fix upgrades the code to generate a json legend for multiple layers.

A review would be appreciated. Thanks, 
  
Stijn

**Comment by weskamm** [comment]
Thanks, changes look good to me. But please remove the whitespace changes and added new empty lines, as these are unrelated and make the diff harder to read

**Comment by stijn-at-work** [comment]
Something seems wrong with the automated tests. My first commit passes the tests. My second commit did not. My third commit reverts the second and still fails. This seems odd. Could you have a look, please? thanks.

**Comment by weskamm** [comment]
@stijn-at-work I know this is not an issue of your PR. Last week github actions started having issues to install packages in debian machines. I upgraded the ubuntu version that the runner uses, but things got a lot worse. Still figuring out what went wrong.

You should just wait till i fixed it and after that you may clanup your commit history again :-)

**Comment by stijn-at-work** [comment]
Thanks for the update. I will wait for your fix. Greetings, Stijn

**Comment by weskamm** [comment]
I think the test pipeline of the current master should be working again. You either need to cleanup your commit history or create a new pr with the changes

**Comment by stijn-at-work** [comment]
thanks Johannes. I will give it a try. I have no experience in cleaning up my commit history. Which git commands do you suggest? Rebase? How does that work?

(So far i used `git checkout [commit id] .` to go back in time to an earlier commit. This does not clean up anything. It simple goes back to an earlier version of the code and create a new commit.)

**Comment by weskamm** [comment]
This PR has changes in 78 files with lots of things you added by accident.
One option would be to go back to master branch, pull the latest changes, create a new branch and just add your own changes (i guess the changes are in the first 3 commits here). Than you can create a new PR with that branch

**Comment by stijn-at-work** [comment]
Yes, good one. I will do it like that.

**Pull request closed without merging**
