### PR TITLE
Take into account use_grid_names for demo service

### PR DESCRIPTION
**Pull request by drnextgis**
Fix for issue described here: https://github.com/mapproxy/mapproxy/issues/317. I've faced with the same behaviour.

### CODE REVIEW

**Comment by drnextgis** [comment]
@olt please review this PR.

**Comment by olt** [comment]
This breaks the WMTS demo. Can you look into this? Thanks.

**Comment by drnextgis** [comment]
I've fixed WMTS demo.

**Comment by olt** [comment]
Thanks for the quick fix!

**Pull request merged**
