### PR TITLE
Fix for #445: always query WMS server in supported SRS

### PR DESCRIPTION
**Pull request by b3nn0**
See description in #445.

### CODE REVIEW

**Comment by weskamm** [comment]
Any ideas why the test is failing?

**Comment by b3nn0** [comment]
Click on the Details link and you will see. That's not related to by PR, but to the test setup:
```
AttributeError: module 'PIL' has no attribute 'PILLOW_VERSION'
```

**Comment by weskamm** [comment]
Do you have a fix for that or an idea, why other pipelines pass?

**Comment by b3nn0** [comment]
I would imagine that it's fixed upstream already (but didn't check). Apparently the CI scripts were broken when I submitted my PR in february (or the test itself).
Check other PRs from around the same time. They have the same issue.
E.g. https://github.com/mapproxy/mapproxy/pull/411

**Comment by weskamm** [comment]
Then please rebase your branch / this PR on the current master

**Comment by b3nn0** [comment]
Done.

**Comment by weskamm** [comment]
any objections @olt ?

**Comment by olt** [comment]
Can you add a comment like: "srs can be equal while still having a different srs_code (EPSG:3857/900913), make sure to use a supported srs_code"?

**Comment by b3nn0** [comment]
Done.

**Comment by weskamm** [comment]
Thanks for your contribution!

**Pull request merged**
