### PR TITLE
feat: add plugin interface to intercept any requests before they are handled

### PR DESCRIPTION
**Pull request by simonseyock**
title says it all.

### CODE REVIEW

**Comment by weskamm** [comment]
This should be already possible as described here i guess:
https://mapproxy.github.io/mapproxy/latest/auth.html#wsgi-filter-middleware
?

**Comment by simonseyock** [comment]
It might be possible, but a plugin is easy to install for the end customer and this extension opens up new ways to write plugins for MapProxy. So I would prefer doing it this way.

But one could argue that it should not be possible for a plugin to work at such a crucial point, potentially breaking anything. I think it is ok, though. The plugin could break the main software in a thousand other ways as well.

**Comment by weskamm** [comment]
The difficulty of using plugins is more or less the same as using a middleware, both do not require much work.
And intercepting requests is proven to work in the middleware, we are using it for several years.
But i dont mind having the additional option to intercept in plugins, so thumbs up from my side.

**Review by weskamm — APPROVED** [review]
Can you add doc / example in a follow up PR?

**Pull request merged**
