### PR TITLE
Add coverage based layer clipping

### PR DESCRIPTION
**Pull request by ramunasd**
This is very helpful when few layers must be merged and source doesn't provides transparent images.

### CODE REVIEW

**Comment by olt** [comment]
Thanks for implementing this!

I noticed, that you changed the BandMerger API to work like the LayerMerger. The LayerMerger is initialized before each merge, the BandMerger is only initialized once in the config loader (and configured with add_ops). That is the reason, that BandMerger gets the sources passed to the `merge` call, and not by calling `add`.  Now the sources of the BandMerger will grow indefinitely. 


BTW: The failed tests are related to S3 and I just pushed a change, that hopefully should fix these errors.

**Comment by ramunasd** [comment]
Thanks @olt, i will restore BandMerger

**Comment by olt** [comment]
Thanks for the update!
My latest changes introduced a conflict. I will fix this while merging your changes and checking that the union/diff/intersection coverages are working as well.

**Comment by ramunasd** [comment]
Thanks @olt , it took a while to solve all inconsistencies in code.
I've noticed that `mapproxy-util server-develop` throws warning about unknown property `clip`. Do You have any clue why it happens? Config spec has this property.

**Comment by olt** [comment]
Hmm, I'm not getting any warnings.

Can you try the mapproxy/clip_coverage branch? https://github.com/mapproxy/mapproxy/compare/clip_coverage

I added support for the new union/diff/intersection coverages and added code to handle multipolygon results from the buffer call.

You added ``clip: true`` to the seeding example in the documentation, this was by accident right?

**Comment by ramunasd** [comment]
I've tested clipping and everything looks good. Except one small bug - after refactor i left wrong return type at `mapproxy/cache/tile.py:296`. Should be `return (None, None)`

**Comment by olt** [comment]
The missing parentheses? That's fine. The comma defines a tuple, not the parentheses.

**Comment by ramunasd** [comment]
LGTM :+1: we can merge that

**Pull request merged**
